
server:
  port: 5000
  context-path: /uaa

management:
  security:
    enabled: false
  context-path: /mgmt
  health:
      rabbit:
        enabled: false

eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    hostname: 127.0.0.1
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
      management.context-path: ${server.context-path}${management.context-path}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@${SPRING_CLOUD_EUREKA_URI:127.0.0.1:8761}/eureka/

spring:
  profiles:
    active: dev
  application:
    name: auth-service
#  datasource:
##    url: jdbc:mysql://11.11.136.121:32341/cloud?useSSL=false
##    username: root
##    password: YvhaLQbh4eKcTnO1
#    initialize: true
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://11.11.136.121:32341/cloud?useSSL=false
#    username: admin
#    password: 1234
  rabbitmq:
    host: 11.11.136.121
    port: 32086
    username: user
    password: password
    listener:
      simple:
        concurrency: 2
        max-concurrency: 2
  sleuth:
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"

#  jpa:
#    show-sql: true
---
spring:
  profiles: ocp
server:
  port: 8080

